language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t ajmason/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true ajmason/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "Docker-React"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-1-153475131564"
  bucket_path: "Docker-React"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"