language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t ajmason/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true ajmason/docker-react npm run test